const CONSTANTS = {
	FETCH_ITEMS_INIT: 'FETCH_ITEMS_INIT',
	FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
	FETCH_ITEMS_FAIL: 'FETCH_ITEMS_FAIL',
	FETCH_MENU_INIT: 'FETCH_MENU_INIT',
	FETCH_MENU_SUCCESS: 'FETCH_MENU_SUCCESS',
	FETCH_MENU_FAIL: 'FETCH_MENU_FAIL',
	FETCH_SECTIONS_INIT: 'FETCH_SECTIONS_INIT',
	FETCH_SECTIONS_SUCCESS: 'FETCH_SECTIONS_SUCCESS',
	FETCH_SECTIONS_FAIL: 'FETCH_SECTIONS_FAIL'
}

export default CONSTANTS;